matrix:
- name: Python Source
  aspell:
    lang: en
    d: en_US
    camel-case: true
  sources:
  - 'rosbot*/**/*.py'

  dictionary:
    encoding: utf-8
    output: wordlist.dic
    wordlists:
    - .wordlist.txt

  pipeline:
  - pyspelling.filters.python:
      comments: true

- name: Markdown sources
  aspell:
    lang: en
    d: en_US
    camel-case: true
  sources:
  - 'rosbot*/**/*.md'
  - 'rosbot*/**/*.txt'
  dictionary:
    encoding: utf-8
    output: wordlist.dic
    wordlists:
    - .wordlist.txt

  pipeline:
  - pyspelling.filters.text

- name: XML sources
  aspell:
    lang: en
    d: en_US
    camel-case: true
  sources:
  - 'rosbot*/**/*.xacro'
  - 'rosbot*/**/*.urdf'
  - 'rosbot*/**/*.xml'
  dictionary:
    encoding: utf-8
    output: wordlist.dic
    wordlists:
    - .wordlist.txt

  pipeline:
  - pyspelling.filters.xml
