#!/usr/bin/env python3

# Copyright 2024 Husarion sp. z o.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import signal
import sys

from ament_index_python.packages import get_package_share_directory
from rosbot_utils.mcu_manager_ftdi import McuManagerFTDI
from rosbot_utils.mcu_manager_uart import McuManagerUART

# Global variable to hold the subprocess reference
subproc = None


def signal_handler(sig, frame):
    global subproc
    if subproc:
        print("Terminating the flashing process...")
        subproc.terminate()
    sys.exit(0)


def main(args=None):
    global subproc

    # Setting up the signal handler
    signal.signal(signal.SIGINT, signal_handler)

    parser = argparse.ArgumentParser(description="Flash ROSbot Firmware")
    _robot_model_env = os.getenv("ROBOT_MODEL")
    parser.add_argument(
        "--robot-model",
        required=_robot_model_env is None,
        default=_robot_model_env,
        choices=["rosbot", "rosbot_xl"],
        help="Specify the robot model",
    )
    parser.add_argument(
        "--usb",
        action="store_true",
        help="Flash via USB. Automatically set for ROSbot XL; other ROSbots use UART by default. (You can flash firmware to ROSbot via USB-A from your PC)",
    )
    parser.add_argument("-f", "--file", help="Specify the firmware file")
    parser.add_argument(
        "-p",
        "--port",
        default="/dev/rosbot",
        help="Specify the communication port",
    )
    args = parser.parse_args(args)

    robot_model = args.robot_model
    if robot_model == "rosbot_xl":
        args.usb = True

    rosbot_utils = get_package_share_directory("rosbot_utils")
    robot_firmware = os.path.join(rosbot_utils, "firmware", robot_model, "v1.0.0-jazzy.bin")
    firmware = args.file if args.file else robot_firmware

    try:
        if args.usb:
            port = args.port
            udev_rules = "/etc/udev/rules.d/99-rosbot.rules"

            if not os.path.exists(port):
                print(f"ERROR: Device {port} not found. Is it connected?")
                sys.exit(1)
            if not os.path.exists(udev_rules):
                print(
                    f"ERROR: No access to device {port}.\nInstall udev rules first:\n  ros2 run rosbot_utils install_udev_rules"
                )
                sys.exit(1)

            mcu_manager = McuManagerFTDI(port)
            mcu_manager.flash_firmware(firmware)
        else:
            mcu_manager = McuManagerUART()
            mcu_manager.flash_firmware(firmware)
        print("Firmware flashing completed successfully!")
    except Exception as e:
        print(f"ERROR: {e}")


if __name__ == "__main__":
    main()
