#!/usr/bin/env python3

# Copyright 2024 Husarion sp. z o.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import numpy as np
import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, QoSReliabilityPolicy
from sensor_msgs.msg import Image


class LEDStripWavePublisher(Node):
    def __init__(self):
        super().__init__("led_strip_manager")
        qos_profile = QoSProfile(depth=1, reliability=QoSReliabilityPolicy.BEST_EFFORT)
        self.pub = self.create_publisher(Image, "led_strip", qos_profile)
        self.create_timer(0.04, self.tick)

        self.N_LEDS = 18
        self.SPEED = 0.14
        self.WAVE_WIDTH = 2.3
        self.MAX_PHASE = 9  # Depend on number of leds in segment

        self.phase = -5.0

    def tick(self):
        self.phase = (self.phase + self.SPEED) % self.MAX_PHASE

        idx = np.arange(self.N_LEDS)

        dist = np.where(
            idx < 5, np.abs(idx - 0.5), np.where(idx > 12, np.abs(idx - 16.5), np.abs(idx - 8.5))
        )

        color = np.where(((5 <= idx) & (idx <= 12))[:, None], [255, 255, 255], [255, 0, 0])

        if self.phase < self.WAVE_WIDTH:
            brightness = self.phase / self.WAVE_WIDTH
            offset = self.phase - self.WAVE_WIDTH
            intensity = brightness * np.clip(1 - np.abs(dist - offset) / self.WAVE_WIDTH, 0.0, 1.0)
        else:
            offset = self.phase - self.WAVE_WIDTH
            intensity = np.clip(1 - np.abs(dist - offset) / self.WAVE_WIDTH, 0.0, 1.0)

        pixels = (color * intensity[:, None]).astype(np.uint8)

        msg = Image()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.height, msg.width = 1, self.N_LEDS
        msg.encoding = "rgb8"
        msg.step = self.N_LEDS * 3
        msg.data = pixels.tobytes()

        self.pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    rclpy.spin(LEDStripWavePublisher())
    rclpy.shutdown()


if __name__ == "__main__":
    main()
