---
# Custom components (own URDF + mesh): https://github.com/husarion/husarion_components_description#custom-component
components:
  - type: rplidar_s3
    parent_link: cover_link
    xyz: -0.01 0.0 0.0
    rpy: 0.0 0.0 0.0

  - type: custom
    package: rosbot_description
    file: urdf/rosbot_xl/components/man01_bracket.urdf.xacro
    macro_name: man01_bracket
    name: man01_bracket
    parent_link: link5
    xyz: 0.026 0.0 0.01
    rpy: 0.0 0.0 0.0

  - type: zed_m
    parent_link: man01_bracket_camera_mount_link
