# Run `xhost +local:docker` before starting the container to allow GUI applications to connect to the X server.

x-common-config:
  &common-config
  network_mode: host
  ipc: host

services:
  rosbot:
    image: husarion/rosbot-gazebo:jazzy
    <<: [ *common-config]
    runtime: nvidia # Remove if do not have NVIDIA GPU
    devices:
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input:ro # Joystick
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/ros2_ws/src/rosbot_ros/docker/dds-config-udp.xml
      - DISPLAY=${DISPLAY:?[Error] No display found.}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch rosbot_gazebo simulation.yaml
        robot_model:=${ROBOT_MODEL:?[Error] Specify robot model}
