x-common-config:
  &common-config
  restart: unless-stopped
  network_mode: host
  ipc: host

services:
  rosbot:
    image: husarion/rosbot:jazzy
    <<: *common-config
    devices:
      - /dev/input # Joystick
      - /dev/manipulator # Manipulator
      - /dev/rosbot # MCU
      - /dev/bus/usb # FTDI
      - /dev/snd # Sound
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/ros2_ws/src/rosbot_ros/docker/dds-config-udp.xml
    command: >
      ros2 launch rosbot_bringup rosbot_xl.yaml
        configuration:=basic
