services:
  rosbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.hardware
    network_mode: host
    ipc: host
    devices:
      - /dev/ttyUSB0
      - /dev/bus/usb/ # FTDI
    command: >
      ros2 launch rosbot_bringup combined.launch.py
        mecanum:=${MECANUM:-False}
        serial_port:=/dev/ttyUSB0
        serial_baudrate:=576000
