x-common-config:
  &common-config
  restart: unless-stopped
  network_mode: host
  ipc: host

services:
  rosbot:
    image: husarion/rosbot:jazzy
    <<: *common-config
    devices:
      - /dev/ttySERIAL # MCU communication port
      - /dev/gpiomem
      - /dev/gpiochip4 # For RPi 4 or ThinkerBoard set to /dev/gpiochip0
      - /dev/input # Joystick
      - /dev/bus/usb # FTDI
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/ros2_ws/src/rosbot_ros/docker/dds-config-udp.xml
    command: >
      ros2 launch rosbot_bringup rosbot.yaml
