services:
  rosbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.hardware
    network_mode: host
    ipc: host
    restart: unless-stopped
    devices:
      - ${SERIAL_PORT:-/dev/ttyUSB0}
      - /dev/bus/usb/ # FTDI
    command: >
      ros2 launch rosbot_bringup combined.launch.py
        mecanum:=${MECANUM:-False}
        namespace:=${ROBOT_NAMESPACE:-rosbot}
        serial_port:=${SERIAL_PORT:-/dev/ttyUSB0}
        serial_baudrate:=576000
