ARG ROS_DISTRO=humble

FROM husarnet/ros:${ROS_DISTRO}-ros-core

WORKDIR /ros2_ws

ENV HUSARION_ROS_BUILD_TYPE=simulation
ENV PIP_BREAK_SYSTEM_PACKAGES=1

COPY .. src/rosbot_ros

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
        python3-pip \
        ros-dev-tools \
        stm32flash \
        ros-${ROS_DISTRO}-teleop-twist-keyboard && \
    # Setup workspace
    vcs import src < src/rosbot_ros/rosbot/rosbot_${HUSARION_ROS_BUILD_TYPE}.repos && \
    vcs import src < src/rosbot_ros/rosbot/manipulator.repos && \
    # Install dependencies
    rosdep init && \
    rosdep update --rosdistro $ROS_DISTRO && \
    rosdep install --from-paths src -y -i && \
    # Build
    source /opt/ros/$ROS_DISTRO/setup.bash && \
    colcon build --packages-up-to rosbot --cmake-args -DCMAKE_BUILD_TYPE=Release && \
    # Get version
    echo $(cat /ros2_ws/src/rosbot_ros/rosbot/package.xml | grep '<version>' | sed -r 's/.*<version>([0-9]+.[0-9]+.[0-9]+)<\/version>/\1/g') >> /version.txt && \
    # Size optimization
    export SUDO_FORCE_REMOVE=yes && \
    apt-get remove -y \
        ros-dev-tools && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
