#!/usr/bin/env python3

# Copyright 2024 Husarion sp. z o.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import signal
import sys

import requests
from ament_index_python.packages import get_package_share_directory

from rosbot_utils.mcu_manager_ftdi import McuManagerFTDI
from rosbot_utils.mcu_manager_uart import McuManagerUART

# Global variable to hold the subprocess reference
subproc = None


def signal_handler(sig, frame):
    global subproc
    if subproc:
        print("Terminating the flashing process...")
        subproc.terminate()
    sys.exit(0)


def download_firmware(firmware_url, firmware_path):
    response = requests.get(firmware_url, allow_redirects=True)
    if response.status_code == 200:
        with open(firmware_path, "wb") as f:
            f.write(response.content)
        print("Firmware downloaded successfully.")
    else:
        raise Exception(f"Failed to download firmware: HTTP {response.status_code}")


def find_firmware_file(path, robot_model):
    rosbot_link = (
        "https://github.com/husarion/rosbot_ros2_firmware/releases/download/0.11.0/firmware.bin"
    )
    rosbot_xl_link = (
        "https://github.com/husarion/rosbot_firmware/releases/download/v1.4.0/firmware.bin"
    )
    robot_download_link = {"rosbot": rosbot_link, "rosbot_xl": rosbot_xl_link}

    if not path:
        print("Downloading firmware...")
        download_firmware(robot_download_link[robot_model], path)

    return path


def main(args=None):
    global subproc

    # Setting up the signal handler
    signal.signal(signal.SIGINT, signal_handler)

    parser = argparse.ArgumentParser(description="Flash ROSbot Firmware")
    parser.add_argument(
        "--robot-model",
        required=True,
        default=os.getenv("ROBOT_MODEL"),
        choices=["rosbot", "rosbot_xl"],
        help="Specify the robot model",
    )
    parser.add_argument(
        "--usb",
        action="store_true",
        help="Flash via USB. Automatically set for ROSbot XL; other ROSbots use UART by default. (You can flash firmware to ROSbot via USB-A from your PC)",
    )
    parser.add_argument("-f", "--file", help="Specify the firmware file")
    parser.add_argument(
        "-b",
        "--baudrate",
        type=int,
        default=921600,
        help="Specify the serial communication baudrate",
    )
    args = parser.parse_args(args)

    robot_model = args.robot_model
    if robot_model == "rosbot_xl":
        args.usb = True

    rosbot_utils = get_package_share_directory("rosbot_utils")
    robot_firmware = os.path.join(rosbot_utils, "firmware", robot_model, "v1.0.0.bin")
    firmware = args.file if args.file else robot_firmware

    try:
        if args.usb:
            mcu_manager = McuManagerFTDI()
            mcu_manager.flash_firmware(firmware, args.baudrate)
        else:
            mcu_manager = McuManagerUART()
            mcu_manager.flash_firmware(firmware, args.baudrate)
        print("Firmware flashing completed successfully!")
    except Exception as e:
        print(f"ERROR: {e}")


if __name__ == "__main__":
    main()
