services:

  navigation:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID

  localization:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID
  
  rplidar:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID

  bridge:
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
      - ROS_DOMAIN_ID

  ros-master:
    network_mode: host
    environment:
      - ROS_IP=127.0.0.1

  rosbot:
    network_mode: host
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311