# Quick Start
#
# 1. run `docker compose up` on the robot
# 3. You can use teleop_twist_keyboard to control the robot in robot1 namespace:
# `ros2 run teleop_twist_keyboard teleop_twist_keyboard  --ros-args -r __ns:=/robot1`

services:

  rosbot:
    build:
      context: ../
      dockerfile: tools/Dockerfile.dev
    network_mode: host
    ipc: host
    # privileged: true # GPIO
    # devices:
    #   - ${SERIAL_PORT:?err}
    #   - /dev/bus/usb/ #FTDI
    volumes:
      - ../rosbot_utils:/ros2_ws/src/rosbot_utils
    # command: tail -f /dev/null
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: >
      ros2 launch rosbot_bringup bringup.launch.py
        mecanum:=${MECANUM:-False}
        namespace:=rosbot
  rviz:
    image: husarion/rviz2:jazzy-jazzy
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    network_mode: host
    ipc: host
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - ./rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: >
      rviz2 --ros-args -r __ns:=/rosbot -r /tf:=tf -r /tf_static:=tf_static
