ARG ROS_DISTRO=humble
ARG PREFIX=
ARG HUSARION_ROS_BUILD_TYPE=hardware

## =========================== ROS builder ===============================
FROM husarnet/ros:${PREFIX}${ROS_DISTRO}-ros-base AS ros_builder

ARG ROS_DISTRO
ARG PREFIX
ARG HUSARION_ROS_BUILD_TYPE

ENV HUSARION_ROS_BUILD_TYPE=${HUSARION_ROS_BUILD_TYPE}

WORKDIR /ros2_ws
RUN mkdir src

COPY ./ src/

RUN apt-get update && apt-get install -y \
        python3-pip \
        stm32flash

RUN vcs import src < src/rosbot/rosbot_hardware.repos && \
    if [ "$HUSARION_ROS_BUILD_TYPE" == "simulation" ]; then \
        vcs import src < src/rosbot/rosbot_simulation.repos; \
    else \
        rm -rf src/rosbot_gazebo; \
    fi && \
    rm -rf /etc/ros/rosdep/sources.list.d/20-default.list && \
	rosdep init && \
    rosdep update --rosdistro $ROS_DISTRO && \
    rosdep install --from-paths src --ignore-src -y

RUN MYDISTRO=${PREFIX:-ros}; MYDISTRO=${MYDISTRO//-/} && \
    source /opt/$MYDISTRO/$ROS_DISTRO/setup.bash && \
    colcon build --packages-up-to rosbot --cmake-args -DCMAKE_BUILD_TYPE=Release
