<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- wheel defining macro -->
  <xacro:macro name="wheel" params="wheel_radius prefix mecanum">

    <xacro:property name="wheel_separation_x" value="0.106" />

    <xacro:if value="${mecanum}">
      <xacro:property name="wheel_file" value="mecanum" />
      <xacro:property name="wheel_thickness" value="0.0455" />
      <xacro:property name="mass" value="0.153" />

      <xacro:property name="ixx" value="0.000111" />
      <xacro:property name="iyy" value="0.000169" />
      <xacro:property name="izz" value="0.000111" />

      <xacro:property name="wheel_separation_y" value="0.205" />
    </xacro:if>

    <xacro:unless value="${mecanum}">
      <xacro:property name="wheel_file" value="wheel" />
      <xacro:property name="wheel_thickness" value="0.036" />
      <xacro:property name="mass" value="0.074" />

      <xacro:property name="ixx" value="0.000041" />
      <xacro:property name="iyy" value="0.000067" />
      <xacro:property name="izz" value="0.000041" />

      <xacro:property name="wheel_separation_y" value="0.192" />
    </xacro:unless>

    <xacro:if value="${prefix == 'fl'}">
      <xacro:property name="x" value="${wheel_separation_x/2.0}" />
      <xacro:property name="y" value="${wheel_separation_y/2.0}" />
      <xacro:property name="mesh" value="file://$(find rosbot_description)/meshes/${wheel_file}_b.dae" />
      <xacro:property name="visual_rotation" value="${pi}" />
      <xacro:property name="fdir" value="1.0 -1.0 0.0" />
    </xacro:if>
    <xacro:if value="${prefix == 'fr'}">
      <xacro:property name="x" value="${wheel_separation_x/2.0}" />
      <xacro:property name="y" value="${-wheel_separation_y/2.0}" />
      <xacro:property name="mesh" value="file://$(find rosbot_description)/meshes/${wheel_file}_a.dae" />
      <xacro:property name="visual_rotation" value="${pi}" />
      <xacro:property name="fdir" value="1.0 1.0 0.0" />
    </xacro:if>
    <xacro:if value="${prefix == 'rl'}">
      <xacro:property name="x" value="${-wheel_separation_x/2}" />
      <xacro:property name="y" value="${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="file://$(find rosbot_description)/meshes/${wheel_file}_a.dae" />
      <xacro:property name="visual_rotation" value="${0.0}" />
      <xacro:property name="fdir" value="1.0 1.0 0.0" />
    </xacro:if>
    <xacro:if value="${prefix == 'rr'}">
      <xacro:property name="x" value="${-wheel_separation_x/2}" />
      <xacro:property name="y" value="${-wheel_separation_y/2}" />
      <xacro:property name="mesh" value="file://$(find rosbot_description)/meshes/${wheel_file}_b.dae" />
      <xacro:property name="visual_rotation" value="${0.0}" />
      <xacro:property name="fdir" value="1.0 -1.0 0.0" />
    </xacro:if>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="body_link" />
      <child link="${prefix}_wheel_link" />
      <origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0.0 1.0 0.0" />
      <limit effort="1.5" velocity="5.0" />
      <dynamics damping="0.001" friction="0.001" />
    </joint>

    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <mesh filename="${mesh}" scale="1.0 1.0 1.0" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${visual_rotation}" />
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
      </collision>

      <inertial>
        <mass value="${mass}" />
        <inertia ixx="${ixx}" ixy="0.0"    ixz="0.0"
                              iyy="${iyy}" iyz="0.0"
                                           izz="${izz}" />
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link" xmlns:ignition="http://ignitionrobotics.org/schema">
      <collision>
        <surface>
          <friction>
            <ode>
              <mu>1.0</mu>
              <mu2>0.0</mu2>
              <fdir1 ignition:expressed_in="base_link">${fdir}</fdir1>
            </ode>
          </friction>
        </surface>
      </collision>
    </gazebo>

  </xacro:macro>
</robot>