---
name: Industrial CI
on:
    workflow_call:
    workflow_dispatch:
    push:

jobs:
    black:
        name: Black
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Black
              uses: psf/black@23.11.0
              with:
                  options: --line-length=99

    spellcheck:
        name: Spellcheck
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Spellcheck
              uses: rojopolis/spellcheck-github-actions@0.33.1

    ros_industrial_ci:
        name: ROS Industrial CI
        runs-on: ubuntu-22.04
        timeout-minutes: 30 # Set the job timeout to 30 minutes
        needs:
            - black
            - spellcheck
        strategy:
            fail-fast: false
            matrix:
                ROS_DISTRO: [humble]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Act + Docker fix
              run: |
                  sudo chown runner:docker /var/run/docker.sock

            - name: Copy to src
              run: |
                  mkdir -p src
                  find . -maxdepth 1 -not -name src -not -name . -exec mv {} src/ \;

            - name: Clone installation requirements
              shell: bash
              run: |
                  python3 -m pip install -U vcstool
                  vcs import src < src/rosbot/rosbot_hardware.repos && vcs import src < src/rosbot/rosbot_simulation.repos

            - name: Copy only diff_drive_controller and imu_sensor_broadcaster, waits for features from ros2-control
              shell: bash
              run: |
                  cp -r src/ros2_controllers/diff_drive_controller src/
                  cp -r src/ros2_controllers/imu_sensor_broadcaster src/
                  rm -rf src/ros2_controllers

            - name: Remove all tests
              shell: bash
              run: find . -type f -name "test_*" -exec rm -rf {} \;

            - name: Running ROS Industrial CI
              uses: ros-industrial/industrial_ci@master
              env:
                  ROS_DISTRO: ${{matrix.ROS_DISTRO}}
                  DOCKER_IMAGE: ros:${{matrix.ROS_DISTRO}}-ros-base
                  IMMEDIATE_TEST_OUTPUT: true
