---
name: CI
on:
  workflow_dispatch:
  push:

jobs:

  pre-commit:
    name: Pre-commit
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-pre-commit.yml@master
    with:
      ros_distro: jazzy

  ros_test:
    name: ROS Test
    uses: ./.github/workflows/run-tests.yaml

  build_docker:
    name: Build Docker
    needs: ros_test
    if: github.ref == 'refs/heads/jazzy'
    uses: ./.github/workflows/build-docker.yaml
    secrets: inherit
    with:
      branch_name: ${{ github.ref_name }}
      build_type: development
