---
name: CI

on:
  push:

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yaml

  bump:
    name: Bump
    needs: tests
    if: ${{ (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name
      == 'workflow_dispatch' }}
    uses: ./.github/workflows/bump.yaml
