---
name: Run tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Run tests ${{ matrix.build_type }} build type
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    strategy:
      matrix:
        build_type: [simulation, hardware]
    env:
      HUSARION_ROS_BUILD_TYPE: ${{ matrix.build_type }}
      PIP_BREAK_SYSTEM_PACKAGES: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          vcs-repo-file-url: |
            rosbot/rosbot_${{ env.HUSARION_ROS_BUILD_TYPE }}.repos
            rosbot/manipulator.repos
          target-ros2-distro: jazzy
          # rosbot_bringup and rosbot_gazebo works only locally
          colcon-defaults: |
            {
              "build": {
                "packages-up-to": ["rosbot"]
              },
              "test": {
                "packages-up-to": ["rosbot"],
                "packages-select-regex": ["rosbot*"],
                "packages-skip": ["rosbot_bringup", "rosbot_gazebo"]
              }
            }
