---
name: Run tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Run tests ${{ matrix.build_type }} build type
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    env:
      PIP_BREAK_SYSTEM_PACKAGES: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          vcs-repo-file-url: |
            rosbot/rosbot_hardware.repos
            rosbot/rosbot_simulation.repos
          target-ros2-distro: jazzy
          # rosbot_bringup and rosbot_gazebo works only locally
          colcon-defaults: |
            {
              "test": {
                "packages-select-regex": ["rosbot*"],
                "packages-skip": ["rosbot_bringup", "rosbot_gazebo"]
              }
            }
