---
name: Run tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Run tests ${{ matrix.build_type }} build type
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [simulation, hardware]
    env:
      HUSARION_ROS_BUILD_TYPE: ${{ matrix.build_type }}
      PIP_BREAK_SYSTEM_PACKAGES: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.7.13
        with:
          use-ros2-testing: true

      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          vcs-repo-file-url: |
            ${{ github.workspace }}/rosbot/rosbot_${{ env.HUSARION_ROS_BUILD_TYPE }}.repos
            ${{ github.workspace }}/rosbot/manipulator.repos
          target-ros2-distro: humble
          # rosbot_bringup and rosbot_gazebo works only locally
          colcon-defaults: |
            {
              "build": {
                "packages-up-to": ["rosbot"]
              },
              "test": {
                "packages-up-to": ["rosbot"],
                "packages-select-regex": ["rosbot*"],
                "packages-skip": ["rosbot_bringup", "rosbot_gazebo"]
              }
            }
